### ISSUE TITLE
Check "4.5_enable_apparmor" too narrow

### ISSUE THREAD

**Issue by TheFlipside** [hardenedlinux/harbian-audit#14]
The check "4.5_enable_apparmor" from /harbian-audit/bin/hardening/4.5_enable_apparmor.sh is only checking for the kernel flags "apparmor=1" and "security=apparmor" in the file "/etc/default/grub".
But at least on debian based systems it is possible to set these settings in configurations files at "/etc/default/grub.d/".
The check is not taking into account that these settings could be separated from the main configuration.

In general a more suitable check would be to see if the keywords are present in "/proc/cmdline".

**Comment by Samson-W** [comment]
Thank you very much for your report on this bug.  
Here are the details of the fix:  Because after Debian 10, AppArmor is installed by default and is a system service. Therefore, before the Debian 10 version, the method you recommended is used to check whether there is an AppArmor configuration in /proc/cmdline, and in Debian 10, the AppArmor service is checked.
