### ISSUE TITLE
auditd scripts only inspect /etc/audit/rules.d/audit.rules

### ISSUE THREAD

**Issue by zumohcv** [hardenedlinux/harbian-audit#19]
It appears that the script files which audit the `auditd` configuration only ever inspect the default configuration file which is located at `/etc/audit/rules.d/audit.rules`. Since it is possible (and probably recommended because of updates) to create additional files in the `/etc/audit/rules.d/` directory, I think it would be better to instead use the file `/etc/audit/audit.rules`, which is – at least on Debian 10 – a file which is automatically generated from the entire contents of `/etc/audit/rules.d/` when `auditd` is restarted or `augenrules` is run manually. It contains all rules, regardless of the file they were defined in, and hence would make detection of missing rules easier and less prone to false negatives.

Something you could both consider a benefit and drawback of this change is that, unless the `audit.rules` file is manually re-generated, it only considers the *running* configuration of `auditd`.

I generated [a patch for the above-mentioned changes](https://gist.github.com/zumohcv/82e110be3c7df985db9def6156f5e5a2), however, it's also possible to make the adjustments with one simple `sed` command:

```batch
sed -i 's#/etc/audit/rules.d/audit.rules#/etc/audit/audit.rules#' bin/hardening/*.sh
```

**Comment by Samson-W** [comment]
First of all, thank you for your feedback. 

You said is correct, but only in the case of --audit. /etc/audit/audit.d/audit.rules is a static configuration file, but the /etc/audit/audit.rules file is not necessarily the runtime configuration of the current system? The result of using the auditctl command is to accurately obtain the runtime status. When executing --apply, add the missing audit rules to /etc/audit/audit.d/audit.rules to automatically generate rules.  

So, the modification plan you submit will cause the --apply to be unavailable.

**Comment by Samson-W** [comment]
Why not use the auditctl command to check the rule items at runtime? It is because there are many ways to write audit rules, or there will be a certain deviation in the wording, which is not conducive to automatic inspection. For example, the following two ways of writing are the same:

auditctl -w /etc/shadow -p wa
auditctl -a always,exit -F path=/etc/shadow -F perm=wa

Automatically generated by the configuration of /etc/audit/audit.d/audit.rules, then the original rules will be replaced in the end. And this project's --apply will perform at least 3 restart operations to complete the repairable items, so the auditd's rules when the system is running are also the rules in /etc/audit/audit.d/audit.rules .

**Comment by zumohcv** [comment]
Ah, right. Sorry. I'm only using the `--audit` functionality on my server, so I didn't think about the `--apply` version at all 👀

You're right, changing the file path to `/etc/audit/audit.rules` would make any changes done by the `--apply` operation disappear once `auditd` restarts, since the file would be re-generated.

It would still be great if `harbian-audit` could consider other files in `/etc/audit/audit.d/`, but if that's not possible without breaking existing functionality, I guess that's just how it is.

Thank you for your time anyway! 🙂
